// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZbFibvZ_ElDHxXXxd5L62z1InBYrowE',
    appId: '1:477487933783:web:305356b1b18c8c7cd5f612',
    messagingSenderId: '477487933783',
    projectId: 'animalcarelk',
    authDomain: 'animalcarelk.firebaseapp.com',
    storageBucket: 'animalcarelk.appspot.com',
    measurementId: 'G-20XHS2Y28D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjf36_8ob0H43sXs-QR3cZumGy7c2gCg',
    appId: '1:477487933783:android:20b708419613078bd5f612',
    messagingSenderId: '477487933783',
    projectId: 'animalcarelk',
    storageBucket: 'animalcarelk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Cs_mB9G5eYE5m6nZWGaiSL5tPx-JE54',
    appId: '1:477487933783:ios:c7f543e93ff5ee40d5f612',
    messagingSenderId: '477487933783',
    projectId: 'animalcarelk',
    storageBucket: 'animalcarelk.appspot.com',
    iosClientId: '477487933783-8rdut49mmnema9s83ksnn04aqhhuu07u.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalcarelk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Cs_mB9G5eYE5m6nZWGaiSL5tPx-JE54',
    appId: '1:477487933783:ios:c7f543e93ff5ee40d5f612',
    messagingSenderId: '477487933783',
    projectId: 'animalcarelk',
    storageBucket: 'animalcarelk.appspot.com',
    iosClientId: '477487933783-8rdut49mmnema9s83ksnn04aqhhuu07u.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalcarelk',
  );
}
